version: '3.8'
services:
  my-jupyter-datascience:
    image: my-jupyter-datascience:latest
    ports:
      - "8890:8888"
    environment:
      - JUPYTER_TOKEN=${MY_SECRET_KEY:-Contraseña}
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ${MY_DIR:-${PWD}}:/home/jovyan/work

  jupyter-spark:
    image: jupyter/pyspark-notebook:latest
    ports:
      - "8889:8888"
    environment:
      - JUPYTER_TOKEN=${MY_SECRET_KEY:-Contraseña}
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ${MY_DIR:-${PWD}}:/home/jovyan/work
